### ISSUE TITLE
write_graphite plugin

### ISSUE THREAD

**Issue by ianbamforth** [bloomberg/collectd_plugins-cookbook#5]
Hi,

Sorry if I'm missing something here, but how do you configure the write_graphite plugin with this cookbook?  It requires a format something like:

```
LoadPlugin "write_graphite"
  <Plugin "write_graphite">
    <Node "example">
    some config stuff
    </Node>
</Plugin
```

..but how do you setup attributes such that the Node bit gets created?  The other plugins I've configured so far don't require the extra level of tags, so are simple.

**Comment by sh9189** [comment]
You need to setup an attribute called `id` for node name part.
For example,

``` ruby
node.default['collectd-plugins']['write_graphite']['node']['id'] = 'example'
node.default['collectd-plugins']['write_graphite']['host'] = 'localhost'
```

**Comment by itsSaad** [comment]
this helped. didn't find any documentation for this actually. :+1:
